"""
Base Strategy Class

Defines the interface for all trading strategies.
"""

from enum import Enum
from typing import Dict, Any, Optional
from dataclasses import dataclass
import pandas as pd


class SignalType(Enum):
    """Type of trading signal."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    CLOSE = "close"


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    
    type: SignalType
    confidence: float  # 0.0 to 1.0
    reason: str
    metadata: Optional[Dict[str, Any]] = None
    
    def __str__(self):
        return f"Signal({self.type.value}, confidence={self.confidence:.2f}, reason='{self.reason}')"


class BaseStrategy:
    """
    Base class for all trading strategies.
    
    Strategies analyze market data and generate trading signals.
    """
    
    def __init__(self, name: str):
        """
        Initialize strategy.
        
        Args:
            name: Strategy name
        """
        self.name = name
        
    def analyze(self, data: pd.DataFrame) -> Signal:
        """
        Analyze market data and generate a trading signal.
        
        Args:
            data: DataFrame with OHLCV data and any additional indicators
                  Required columns: open, high, low, close, volume
                  
        Returns:
            Trading signal
        """
        raise NotImplementedError("Strategy must implement analyze method")
        
    def get_params(self) -> Dict[str, Any]:
        """
        Get strategy parameters.
        
        Returns:
            Dictionary of strategy parameters
        """
        return {}
        
    def set_params(self, params: Dict[str, Any]):
        """
        Set strategy parameters.
        
        Args:
            params: Dictionary of parameters to update
        """
        pass
